using System.Collections;
using System.Collections.Generic;

namespace MaxTek.ERP.DAL;

public interface ITecnicoEngenhariaProdutoAlmoxarifadoCompartimento
{
	IList<MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento> ObterTodosTecnicoEngenhariaProdutoAlmoxarifadoCompartimento();

	IList<MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento> ObterTodosTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(int codigoAlmoxarifado);

	MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento ObterTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(int id);

	MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento ObterTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento TecnicoEngenhariaProdutoAlmoxarifadoCompartimento);

	int InserirTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento TecnicoEngenhariaProdutoAlmoxarifadoCompartimento);

	int AlterarTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(MapTableTecnicoEngenhariaProdutoAlmoxarifadoCompartimento TecnicoEngenhariaProdutoAlmoxarifadoCompartimento, Hashtable camposAlterados);

	int ExcluirTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(int id);

	int ExcluirTodosTecnicoEngenhariaProdutoAlmoxarifadoCompartimento(int codigoAlmoxarifado);
}
